apiVersion: apps/v1
kind: Deployment
metadata:
  name: amir-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amir-node-app
  template:
    metadata:
      labels:
        app: amir-node-app
    spec:
      containers:
        - name: amir-node-app
          image: gcr.io/my-project-amir-387708/amir-node-app:latest
          ports:
            - containerPort: 8080
